#!/usr/bin/env bash

vm_generated_root() {
  printf '%s/generated/simulation/vm\n' "$repo_root"
}

vm_path_run_dir() {
  printf '%s/%s\n' "$(vm_generated_root)" "$HARNESS_RUN_ID"
}

vm_path_set_dir() {
  printf '%s/vm-sets/%s\n' "$(vm_generated_root)" "$LOOPFORGE_VM_SET_ID"
}

vm_paths_apply_canonical() {
  HARNESS_GENERATED_RUN_DIR="$(vm_path_run_dir)"
  HARNESS_VM_SET_DIR="$(vm_path_set_dir)"
  HARNESS_HOST_DIR="$HARNESS_GENERATED_RUN_DIR/host"
  HARNESS_TARGET_DIR="$HARNESS_GENERATED_RUN_DIR/target"
  HARNESS_RENDERED_DIR="$HARNESS_HOST_DIR/rendered"
  HARNESS_RUNTIME_INPUT_DIR="$HARNESS_HOST_DIR/runtime-inputs"
  HARNESS_RENDERED_ENV="$HARNESS_RENDERED_DIR/harness.env"
  HARNESS_RUNTIME_ENV="$HARNESS_RENDERED_DIR/harness.runtime.env"
  HARNESS_VM_INVENTORY_FILE="$HARNESS_RENDERED_DIR/vm-inventory.env"
  HARNESS_MANIFEST_CONTRACT="$HARNESS_RENDERED_DIR/artifact-manifest-contract.txt"
  HARNESS_RUN_MARKER="$HARNESS_GENERATED_RUN_DIR/.loopforge-vm-run.env"
  HARNESS_VM_SET_MARKER="$HARNESS_VM_SET_DIR/.loopforge-vm-set.env"
  HARNESS_EVIDENCE_DIR="$HARNESS_HOST_DIR/evidence/harness"
  HARNESS_LOG_DIR="$HARNESS_HOST_DIR/logs/harness"
  HARNESS_INTEGRATION_EVIDENCE_DIR="$HARNESS_HOST_DIR/evidence/integration"
  HARNESS_INTEGRATION_LOG_DIR="$HARNESS_HOST_DIR/logs/integration"
  HARNESS_EXPORTED_ARTIFACT_DIR="$HARNESS_HOST_DIR/artifacts/exported"
  HARNESS_RETAINED_OUTPUT_BACKUP_DIR="$HARNESS_HOST_DIR/retained-output-backups"
  HARNESS_TARGET_SSH_DIR="$HARNESS_HOST_DIR/target-ssh"
  HARNESS_TARGET_SSH_IDENTITY_FILE="$HARNESS_TARGET_SSH_DIR/ci-operator"
  HARNESS_TARGET_SSH_KNOWN_HOSTS_FILE="$HARNESS_TARGET_SSH_DIR/known_hosts"
  HARNESS_GERRIT_EVIDENCE_DIR="$HARNESS_TARGET_DIR/evidence/gerrit"
  HARNESS_GERRIT_LOG_DIR="$HARNESS_TARGET_DIR/logs/gerrit"
  HARNESS_JENKINS_CONTROLLER_EVIDENCE_DIR="$HARNESS_TARGET_DIR/evidence/jenkins-controller"
  HARNESS_JENKINS_CONTROLLER_LOG_DIR="$HARNESS_TARGET_DIR/logs/jenkins-controller"
  HARNESS_JENKINS_AGENT_EVIDENCE_DIR="$HARNESS_TARGET_DIR/evidence/jenkins-agent"
  HARNESS_JENKINS_AGENT_LOG_DIR="$HARNESS_TARGET_DIR/logs/jenkins-agent"

  export HARNESS_GENERATED_RUN_DIR HARNESS_VM_SET_DIR HARNESS_HOST_DIR
  export HARNESS_TARGET_DIR HARNESS_RENDERED_DIR HARNESS_RUNTIME_INPUT_DIR
  export HARNESS_RENDERED_ENV HARNESS_RUNTIME_ENV HARNESS_VM_INVENTORY_FILE
  export HARNESS_MANIFEST_CONTRACT HARNESS_RUN_MARKER HARNESS_VM_SET_MARKER
  export HARNESS_EVIDENCE_DIR HARNESS_LOG_DIR
  export HARNESS_INTEGRATION_EVIDENCE_DIR HARNESS_INTEGRATION_LOG_DIR
  export HARNESS_EXPORTED_ARTIFACT_DIR HARNESS_RETAINED_OUTPUT_BACKUP_DIR
  export HARNESS_TARGET_SSH_DIR HARNESS_TARGET_SSH_IDENTITY_FILE
  export HARNESS_TARGET_SSH_KNOWN_HOSTS_FILE
  export HARNESS_GERRIT_EVIDENCE_DIR HARNESS_GERRIT_LOG_DIR
  export HARNESS_JENKINS_CONTROLLER_EVIDENCE_DIR
  export HARNESS_JENKINS_CONTROLLER_LOG_DIR
  export HARNESS_JENKINS_AGENT_EVIDENCE_DIR HARNESS_JENKINS_AGENT_LOG_DIR
}

vm_path_runtime_inputs() {
  printf '%s\n' "$HARNESS_RUNTIME_INPUT_DIR"
}

vm_path_bounded_log() {
  bounded_log_path_in_dir "$HARNESS_LOG_DIR" "${1:?log name required}"
}
